
version: '3.4'

services:
  githubaction:
    image: githubaction
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
